### PR TITLE
Use UIDL aware logout redirect strategy

### LINKED ISSUE #42: Using AuthenticationContext::logout fails to redirect
Initiating programmatic logout via `AuthenticationContext::logout` results in a UIDL request which fails to redirect the browser to the configured post-logout URL via the default Spring redirect strategy.

Using a custom redirect strategy might be able to detect UIDL requests and act accordingly, e.g. using `Page::setLocation`.

### PR DESCRIPTION
**Pull request by heruan**
Adds a custom UIDL aware logout redirect strategy and calls the logout success-handler inside `UI::accessSynchronously`.

Closes #42

### CODE REVIEW

File: sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java [hunk 1]
```diff
@@ -219,14 +222,17 @@ public void logout() {
...
-                LOGGER.warn("There was an error notifying the OIDC provider of "
-                        + "the user logout", e);
-            }
+            ui.accessSynchronously(() -> {
+                try {
+                    logoutSuccessHandler.onLogoutSuccess(req, res, auth);
+                } catch (IOException | ServletException e) {
+                    // Raise a warning log message about the failure.
+                    LOGGER.warn("There was an error notifying the OIDC "
+                            + "provide of the user logout", e);
```
Comment (tamasmak) [inline sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java:233]: Should be provider instead of provide.

Comment (tamasmak) [inline sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java:233]: Should be provider instead of provide.

**Review by tamasmak — CHANGES_REQUESTED** [review]

File: sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java (hunk 1 above)
Comment (heruan) [reply sso-kit-starter/src/main/java/com/vaadin/sso/starter/SingleSignOnConfiguration.java]: Fixed, thanks!

**Review by tamasmak — APPROVED** [review]
